name: build-rwzfs

on:
  workflow_dispatch:
  schedule:
    - cron: '17 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-rwzfs-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-rwzfs-
          gc-max-store-size-linux: 8G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-rwzfs-
          purge-created: 0
          purge-primary-key: never
          purge-last-accessed: 604800

      - run: nix build --print-build-logs .#nixosConfigurations.rwzfs.config.system.build.toplevel
