name: build-xlthlx

on:
  workflow_dispatch:
  push:
    branches: [master]
  schedule:
    - cron: '17 7 * * *'

jobs:
  build:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v30

      - uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-xlthlx-${{ hashFiles('**/*.nix', 'flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-xlthlx-
          gc-max-store-size-macos: 8G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-xlthlx-
          purge-created: 0
          purge-primary-key: never
          purge-last-accessed: 604800

      - run: nix build --print-build-logs .#darwinConfigurations.xlthlx.config.system.build.toplevel
